"""Add responsible_person

Revision ID: 1f5f05abae1b
Revises: 0003
Create Date: 2026-05-06 15:41:53.319530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5f05abae1b'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assessment_results_assessment_id_fkey'), 'assessment_results', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_results', 'assessments', ['assessment_id'], ['assessment_id'])
    op.drop_constraint(op.f('assessments_patient_hn_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'patients', ['patient_hn'], ['hn'])
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.drop_constraint(op.f('form_tokens_patient_hn_fkey'), 'form_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'form_tokens', 'patients', ['patient_hn'], ['hn'])
    op.alter_column('patients', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint(None, 'form_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('form_tokens_patient_hn_fkey'), 'form_tokens', 'patients', ['patient_hn'], ['hn'], ondelete='CASCADE')
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_patient_hn_fkey'), 'assessments', 'patients', ['patient_hn'], ['hn'], ondelete='CASCADE')
    op.drop_constraint(None, 'assessment_results', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_results_assessment_id_fkey'), 'assessment_results', 'assessments', ['assessment_id'], ['assessment_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
