"""add_follow_up_date_to_patients

Revision ID: 27ddd042ac53
Revises: ff28d1fc63ad
Create Date: 2026-06-14 11:01:37.527957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ddd042ac53'
down_revision: Union[str, Sequence[str], None] = 'ff28d1fc63ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.add_column('patients', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('follow_up_schedules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('patients', sa.Column('responsible_person', sa.String(length=128), nullable=True))
    op.drop_constraint(op.f('patients_line_user_id_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_line_user_id'), 'patients', ['line_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_line_user_id'), table_name='patients')
    op.create_unique_constraint(op.f('patients_line_user_id_key'), 'patients', ['line_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'responsible_person')
    op.drop_column('patients', 'follow_up_schedules')
    op.drop_column('patients', 'follow_up_date')
    op.create_table('documents',
    sa.Column('document_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rag_status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name=op.f('documents_uploaded_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
