"""split user full_name

Revision ID: 493e6d316f5b
Revises: 0019
Create Date: 2026-05-19 17:51:30.121634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e6d316f5b'
down_revision: Union[str, Sequence[str], None] = '0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_form_tokens_patient_schedule'), 'form_tokens', type_='unique')
    op.drop_index(op.f('ix_patients_line_user_id'), table_name='patients')
    op.create_unique_constraint(None, 'patients', ['line_user_id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=64), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), server_default='', nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index(op.f('ix_patients_line_user_id'), 'patients', ['line_user_id'], unique=True)
    op.create_unique_constraint(op.f('uq_form_tokens_patient_schedule'), 'form_tokens', ['patient_hn', 'schedule_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
